project:
  home: "/home/pi/capteur-henao"
  capture: "/home/pi/captures/"
  id_cyclist: "ID2_C2"
camera:
  frame_rate: 25
  resolution:
    small:
      width: 426
      height: 240
    medium:
      width: 768
      height: 432
    large:
      width: 960
      height: 540
lidar:
  unit:
    cm: 1
    inch: 0.393701
  distance:
    warning: 100
    max: 300
gps:
  period_capture: 300